spring:
  ai:
    application:
      name: mcp-host
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-3-7-sonnet-20250219
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            author-tool-server:
              url: http://localhost:8088
              enabled: true
        stdio:
          connections:
            brave-search:
              command: npx.cmd
              args:
                - "-y"
                - "@modelcontextprotocol/server-brave-search"
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}

            filesystem:
              command: npx.cmd
              args:
                - "-y"
                - "@modelcontextprotocol/server-filesystem"
                - "./"

logging:
  level:
    io:
      modelcontextprotocolL: TRACE
    org:
      springframework:
        ai: TRACE